// <auto-generated />
using System;
using Gs1.DigitalLink.Resolver;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gs1.DigitalLink.Resolver.Migrations
{
    [DbContext(typeof(ResolverDbContext))]
    [Migration("20260911133733_InitialResolverSchema")]
    partial class InitialResolverSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalPath")
                        .IsUnique();

                    b.ToTable("LinkDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CanonicalPath = "/01/08690504080008"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CanonicalPath = "/01/08690504080008/10/LOT123"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CanonicalPath = "/414/8690123456789"
                        });
                });

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationIdentifier")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("LinkDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationIdentifier", "Value");

                    b.HasIndex("LinkDefinitionId", "Position")
                        .IsUnique();

                    b.ToTable("LinkIdentifiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ApplicationIdentifier = "01",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Position = 0,
                            Value = "08690504080008"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            ApplicationIdentifier = "01",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Position = 0,
                            Value = "08690504080008"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            ApplicationIdentifier = "10",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Position = 1,
                            Value = "LOT123"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            ApplicationIdentifier = "414",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Position = 0,
                            Value = "8690123456789"
                        });
                });

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("LinkDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("LinkDefinitionId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("LinkDefinitionId", "LinkType", "Language", "MediaType")
                        .IsUnique();

                    b.ToTable("LinkTargets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsDefault = false,
                            Language = "tr",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            LinkType = "gs1:pip",
                            MediaType = "text/html",
                            Url = "https://example.com/tr/products/08690504080008"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            IsDefault = false,
                            Language = "en",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            LinkType = "gs1:pip",
                            MediaType = "text/html",
                            Url = "https://example.com/en/products/08690504080008"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            IsDefault = true,
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            LinkType = "gs1:defaultLink",
                            MediaType = "text/html",
                            Url = "https://example.com/products/08690504080008"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            IsDefault = false,
                            Language = "tr",
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            LinkType = "gs1:pip",
                            MediaType = "text/html",
                            Url = "https://example.com/tr/products/08690504080008/lots/LOT123"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            IsDefault = true,
                            LinkDefinitionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            LinkType = "gs1:defaultLink",
                            MediaType = "text/html",
                            Url = "https://example.com/locations/8690123456789"
                        });
                });

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkIdentifier", b =>
                {
                    b.HasOne("Gs1.DigitalLink.Resolver.LinkDefinition", "LinkDefinition")
                        .WithMany("Identifiers")
                        .HasForeignKey("LinkDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkDefinition");
                });

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkTarget", b =>
                {
                    b.HasOne("Gs1.DigitalLink.Resolver.LinkDefinition", "LinkDefinition")
                        .WithMany("Targets")
                        .HasForeignKey("LinkDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkDefinition");
                });

            modelBuilder.Entity("Gs1.DigitalLink.Resolver.LinkDefinition", b =>
                {
                    b.Navigation("Identifiers");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
